### PR TITLE
Checkstyle task not working

### PR DESCRIPTION
**Pull request by Guardiola31337**
It's related with #111 
Before creating #192 I noticed that `checkstyle.gradle` task defined in `libjava` module wasn't working.
It didn't report anything. It seemed strange to me so I fixed it.
Now, you can review the checkstyle warnings running `$ ./gradlew clean checkstyle`.
Likewise, you can add checkstyle support into `libandroid` module. Let me know if you want me to do it.

### CODE REVIEW

**Comment by zugaldia** [comment]
@Guardiola31337 Thank you for the contribution, you're on a roll :)

@cammace you've been working on this, could you review when you have a chance?

**Comment by Guardiola31337** [comment]
@zugaldia You're welcome!
I don't know what happened with the Bitrise check. I can't see your Bitrise configuration (logically), but let me know if I can help because I tried it on my forked repository and is running without failing.

**Comment by zugaldia** [comment]
@Guardiola31337 you can actually see our [Bitrise config](https://github.com/mapbox/mapbox-java/blob/master/scripts/bitrise.yml) (you can't see the keys though :).

**Comment by Guardiola31337** [comment]
@zugaldia It's true :) But I can't see the log details that you're getting on Bitrise, so I don't know which step is failing.

**Comment by cammace** [comment]
Thanks for the PR @Guardiola31337, I cleaned up the gradle task slightly and set it up for libandroid also. Closing in favor of https://github.com/mapbox/mapbox-java/pull/224

**Pull request closed without merging**
