### PR TITLE
Rename references of `mapIds` to `tileSetIds` 

### PR DESCRIPTION
**Pull request by langsmith**
Resolves https://github.com/mapbox/mapbox-java/issues/1021 by refactoring references of `mapIds` to `tileSetIds`. This pr is the same as https://github.com/mapbox/mapbox-java/pull/1022, but like this pr, #1022 was semver major and shouldn't have been merged just yet. #1022 was reverted, so **this pr** sets up the original refactoring changes for eventual merge to `master`.

### CODE REVIEW

**Comment by zugaldia** [comment]
@langsmith @tobrun Considering that the changes only affect the TileQuery component, it should be possible to update Maps SDK without breaking its public APIs. Does that sound correct?

**Comment by langsmith** [comment]
Yea, that's correct @zugaldia .

**Comment by HeyStenson** [comment]
Thanks for your help on this @langsmith! 🙌  Turns out there were only two little changes that needed to be made.

**Comment by HeyStenson** [comment]
@langsmith Do we need to do anything else to get this over the finish line?

**Comment by langsmith** [comment]
Waiting @HeyStenson 😕 . This pr has semver major changes, so I've thought that we'll do a SEMVER major Java release when we do our next Maps SDK SEMVER major release.

**Pull request merged**
