### PR TITLE
Firebase Test Lab CI integration for app module

### LINKED ISSUE #380: Add CI instrumentation testing
To catch regressions that only show at runtime, we need to hook up the [app](https://github.com/mapbox/mapbox-java/tree/master/mapbox/app) module to Firebase Test Lab and run these tests as part of our PR workflow. Since we don't have any espresso tests in this module, I'm thinking about leveraging the Robo tests from Firebase Test Lab:

> Robo test is a test tool that is integrated with Firebase Test Lab for Android. Robo test analyzes the structure of your app's UI and then explores it methodically, automatically simulating user activities. Unlike the UI/Application Exerciser Monkey test, Robo test always simulates the same user activities in the same order when you use it to test an app on a specific device configuration with the same maximum depth and timeout settings.

cc @zugaldia

### PR DESCRIPTION
**Pull request by tobrun**
Closes #380

### CODE REVIEW

**Comment by zugaldia** [comment]
@tobrun Build is failing in a promising way ;)

image

**Comment by tobrun** [comment]
screen shot 2017-03-07 at 18 58 00

I'm seeing this crash also locally when running it locally on a device ;) crashes at startup.

**Comment by zugaldia** [comment]
@tobrun 🎉 the crash is exactly the one we wanted to prevent. I've fixed it temporarily with https://github.com/mapbox/mapbox-java/pull/381/commits/4a81b302cacf74b2e79fa64e18ea6023f9ee526e and wait for a new CI build.

**Comment by tobrun** [comment]
🙇

**Comment by zugaldia** [comment]
@tobrun this is looking great, let's use it across the board. For now, the current CI issue is a missing access token exception.

**Pull request merged**
