### PR TITLE
Be explicit about features in the README

### PR DESCRIPTION
**Pull request by tmcw**
cc @cammace for the review

### CODE REVIEW

**Comment by cammace** [comment]
I've added the rest of the features mapbox java has for devs. Ready to merge when you are @tmcw

**Comment by zugaldia** [comment]
@cammace Let's add under the Android section replacement for the built-in Android `Geocoder`.

**Comment by tmcw** [comment]
Made the Geocoder mention more explicit. Merging once green.

**Comment by zugaldia** [comment]
> Geocoder input view with autocompletion (drop-in replacement for stock Geocoder view)

Sorry, my bad explaining, this is not accurate. These should be two different items:

- Ready-to-go geocoder input view with autocompletion.
- Drop-in replacement for stock Android Geocoder object.

The first item is a UI element, the second one is a drop in replacement for the [`Geocoder`](https://developer.android.com/reference/android/location/Geocoder.html) object.

**Pull request merged**
