### PR TITLE
Improve User-Agent string

### LINKED ISSUE #92: Improve user agent string
Once https://github.com/mapbox/mapbox-java/pull/91 landed, we started setting a string that looks like this: `MapboxJava/1.2.0 Mac OS X/10.11.5 (x86_64)`

We'd also like to include:
* The name of the Android app (if any)
* Automate the inclusion of the version number in the Java code to avoid inconsistencies.

/cc: @1ec5 @cammace

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #92

### CODE REVIEW

**Comment by zugaldia** [comment]
Looking good though CI is complaining:

> A problem occurred evaluating project ':libjava'.
> Could not get unknown property 'BuildConfigPlugin' for project ':libjava' of type org.gradle.api.Project.

**Comment by ivovandongen** [comment]
>Looking good though CI is complaining

Yeah, having trouble including the project in such a way that both projects can use it (apparently needed when depending on another project directly). Also, generating the `BuildConfig` in any other directory than the main sources doesn't work in Android Studio, but does cmd-line.

For now, I'm going to generate the `BuildConfig` in the main sources with a git ignore entry. This appeases AS, bitrise and cmd line invocation.

**Comment by ivovandongen** [comment]
@zugaldia Added a setter on the builders to add an App name optionally. This results in 2 possible user agents:

- No app name set: `MapboxJava/2.0.0-SNAPSHOT (975537e) Mac OS X/10.11.6 (x86_64)`
- With app name set: `AppName MapboxJava/2.0.0-SNAPSHOT (975537e) Mac OS X/10.11.6 (x86_64)`

**Comment by ivovandongen** [comment]
> Javadoc ain't happy

Should be fxed

**Comment by zugaldia** [comment]
@ivovandongen 👍 Ready to merge then.

**Pull request merged**
