### PR TITLE
[READY FOR REVIEW] Map matching example

### PR DESCRIPTION
**Pull request by cammace**
Placeholder for the map matching example

### CODE REVIEW

**Comment by cammace** [comment]
I can change the trace file if we need something showing more of a difference. Otherwise this example should be ready to merge

cc: @zugaldia

**Comment by cammace** [comment]
closes #87

**Comment by zugaldia** [comment]
@cammace Is the trace file in https://www.mapbox.com/blog/map-matching-api/ any better?

**Comment by cammace** [comment]
Here is what the demo looks like now, you get a perfect match when precision is maxed out at 10. I added a check in the code to make sure the response is "OK", `if(response.code() == 200)`.

ezgif com-video-to-gif 1

**Comment by cammace** [comment]
Changed the trace again, added a missing log output when/if an error occurs and commented more of the code. The trace now looks like:

ezgif com-video-to-gif 3

Examples ready to 🚢, merging now!

**Comment by zugaldia** [comment]
@cammace Love the new route.

**Pull request merged**
