### PR TITLE
RouteLegRefresh: added incidents

### PR DESCRIPTION
**Pull request by RingerJK**

### CODE REVIEW

**Comment by VysotskiVadim** [comment]
@RingerJK , what do you think about adding an example of json with incidents from Directions API and test if it can be serialised to the model?

**Comment by RingerJK** [comment]
> @RingerJK , what do you think about adding an example of json with incidents from Directions API and test if it can be serialised to the model?

that's a good point. Extended current jsons with tests, check the branch

**Review by LukasPaczos — APPROVED** [review]

**Comment by LukasPaczos** [comment]
Ah, could you please also add a changelog to unreleased?

**Comment by RingerJK** [comment]
my bad, I didn't know we started to add changelog for mapbox-java, will cut another PR

**Comment by RingerJK** [comment]
changelog pull request https://github.com/mapbox/mapbox-java/pull/1435

**Pull request merged**
