### PR TITLE
Add check to determine if runtime permissions are required

### PR DESCRIPTION
**Pull request by tobrun**
Refs #419

### CODE REVIEW

**Comment by cammace** [comment]
Looks like CI's failing with this error:
```
:libandroid-telemetry:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/bitrise/src/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/permissions/PermissionsManager.java:55: error: package Build does not exist
    return android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M;
                                                    ^
1 error
:libandroid-telemetry:compileReleaseJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':libandroid-telemetry:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by tobrun** [comment]
Hah, it seems that there aren't any android dependency available there, instead of checking against BUILD.x.xx, we can check against a constant int instead.

**Comment by zugaldia** [comment]
Weird, this is an Android library targeting Nougat, why wouldn't it have `Build.VERSION_CODES` available?

**Comment by cammace** [comment]
The class was just missing the build import. fixed.

**Pull request merged**
