### PR TITLE
Introduce new user agent API

### PR DESCRIPTION
**Pull request by Guardiola31337**
- Adds `newUserAgent(String userAgent)`

👀 @cammace @ericrwolfe @zugaldia

### CODE REVIEW

**Comment by danesfeder** [comment]
@ericrwolfe @Guardiola31337 When I create a new instance `MapboxNavigation`, it will initialize the telem library.  

Will it be initialized with `userAgent` set to "mapbox-navigation-android"?  

If someone launches the drop-in UI, it should be be changed to "mapbox-navigation-android-ui", so I will need to add a line in the UI code after I initialize `MapboxNavigation` to set it to "mapbox-navigation-android-ui" right?

**Comment by ericrwolfe** [comment]
> If someone launches the drop-in UI, it should be be changed to "mapbox-navigation-android-ui", so I will need to add a line in the UI code after I initialize MapboxNavigation to set it to "mapbox-navigation-android-ui" right?

Yep that's correct. Here's where it's done on iOS: 
* Setting the user agent: https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/RouteController.swift#L222-L223
* Setting the user interface flag: https://github.com/mapbox/mapbox-navigation-ios/blob/e4eb39bdece779b29f3c19b916d0eca16b39064c/MapboxNavigation/NavigationViewController.swift#L341-L343

Per my comment above https://github.com/mapbox/mapbox-java/pull/568#pullrequestreview-63761426, you'll probably need to pass a full user agent string with a version, such as `mapbox-navigation-ui-android/0.6.0-SNAPSHOT`, into `newUserAgent()`.

**Comment by danesfeder** [comment]
Okay sounds good - adding to list of things to do in the Nav SDK once MAS lands

**Comment by Guardiola31337** [comment]
> you'll probably need to pass a full user agent string with a version, such as `mapbox-navigation-ui-android/0.6.0-SNAPSHOT`, into `newUserAgent()`.

That's correct.

After initializing telemetry you should add a call to `MapboxTelemetry.getInstance().newUserAgent("<fullUserAgent>");`

Merging it.

**Pull request merged**
