### PR TITLE
Turf example added to testapp

### PR DESCRIPTION
**Pull request by cammace**
Just a place holder for now, I am running into an issue with `TurfMisc.lineSlice`, working off [this example](https://github.com/turf-junkyard/turf-line-slice), I keep getting this error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.gson.JsonObject.addProperty(java.lang.String, java.lang.Number)' on a null object reference
```

Also with `TurfMeasurement.lineDistance` shouldn't I be able to pass in a lineString?

cc: @zugaldia

### CODE REVIEW

**Comment by cammace** [comment]
Originally I had all the turf examples in one activity... terrible idea. I have now separated the turf equations into different activities. Bearing and destination are finished and working great:

For `TurfMeasurement.bearing`:
ezgif com-video-to-gif 4

`TurfMeasurement.destination`:
ezgif com-video-to-gif 5

**Comment by cammace** [comment]
distance example has now been added to the testapp:

`TurfMeasurement.distance`:
ezgif com-video-to-gif 6

**Comment by zugaldia** [comment]
@cammace This is looking great. With the number of examples growing, we're gonna need to add subsections like we do in the SDK's TestApp (can be ticketed separately).

> I am running into an issue with TurfMisc.lineSlice, working off this example, I keep getting this error:

Ticketed here: https://github.com/mapbox/mapbox-java/issues/105

**Comment by zugaldia** [comment]
@cammace This is fixed now via https://github.com/mapbox/mapbox-java/issues/105, feel free to take it up whenever you're ready.

**Comment by cammace** [comment]
Going ahead and merging examples, will open a new PR for the rest of turf examples

**Pull request merged**
