### PR TITLE
Fix for #766:Test missing for public static method in PolylineUtils.java

### PR DESCRIPTION
**Pull request by mghildiy**
Test added.

### CODE REVIEW

**Comment by cammace** [comment]
This is great @mghildiy, thanks for adding these test. I'll let @osana take the charge of pulling this PR into our repo so CI can run, reviewing and getting this merged.

**Comment by cammace** [comment]
Also, if this resolves https://github.com/mapbox/mapbox-java/issues/766, let's make sure we close the issue when this gets merged.

**Comment by osana** [comment]
Created PR #797  from this one

**Comment by cammace** [comment]
Closing since #797 is created and running CI.

**Pull request closed without merging**
