### PR TITLE
Lower API level min SDK to 14

### PR DESCRIPTION
**Pull request by zugaldia**
Fixes https://github.com/mapbox/mapbox-java/issues/575.

### CODE REVIEW

**Comment by zugaldia** [comment]
CI is currently failing due to issues with the Test App depending on libraries (Maps SDK, LOST) that requires 15+. Looks like otherwise the library is in good shape to support 14. Let's revisit once https://github.com/mapbox/mapbox-gl-native/issues/9403 lands.

cc: @cammace

**Comment by langsmith** [comment]
Let's make sure to let the support team know about this because documentation might have to be updated and they periodically answer Help Scout tickets related to min version

**Comment by cammace** [comment]
Note that in 3.0.0 this is a pure java repo and won't have an API level :)

**Comment by zugaldia** [comment]
> Note that in 3.0.0 this is a pure java repo and won't have an API level :)

Correct. This requirement is now for the standalone telemetry library. @electrostat could you keep track of this one?

**Comment by cammace** [comment]
Closing since in 3.0 there will be no API level to lower :)

**Pull request closed without merging**
