### PR TITLE
[Not Ready] started work on geojson docs

### PR DESCRIPTION
**Pull request by cammace**

### CODE REVIEW

**Comment by zugaldia** [comment]
@cammace Still work in progress, or ready for some 👀 ?

**Comment by cammace** [comment]
Ready for a look over. Most documentation came straight from [geojson spec](http://geojson.org/geojson-spec.html)

**Comment by zugaldia** [comment]
Looking good, following the geojson spec is spot on.

I still see a few `TODO`s so I'll let you finish, there's no particular rush for this one.

**Comment by zugaldia** [comment]
@bleege looking great, merging now!

**Pull request merged**
